#!/bin/sh

# start axiom services (i.e. axiom-init)

echo 1 > /proc/sys/vm/overcommit_memory
echo 0 > /proc/sys/kernel/randomize_va_space

[ -e /etc/axiomrc ] && . /etc/axiomrc

case "$1" in
    start)
	modprobe axiom-netdev
	if [ x"${MASTER}" = x"yes" ]; then
  	    axiom-init -m &
	else
	    axiom-init &
	fi
	;;
    stop)
        killall axiom-ethtap
  	killall axiom-init
	modprobe -r axiom-netdev
	;;
    restart|reload)
	"$0" stop
	"$0" start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
